# Generated by Django 5.0.7 on 2024-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdata_email_alter_userdata_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter your phone.'),
        ),
    ]
