# Generated by Django 5.0.7 on 2024-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter your email.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Enter your First Name.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Enter your Last  Name.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='message',
            field=models.CharField(max_length=50, null=True, verbose_name='Enter your message.'),
        ),
    ]
